"""Benign local mutation tests for semantic reproduction comparison.

Requires the complete results/reproduced generated by reproduce.py. No
reference result or original reproduced result is changed.
"""
from pathlib import Path
import copy,json,shutil,subprocess,sys,tempfile,time,resource
ROOT=Path(__file__).resolve().parents[1]

def main():
    start=time.process_time();before=resource.getrusage(resource.RUSAGE_CHILDREN)
    observations=[]
    with tempfile.TemporaryDirectory(prefix='drift-compare-') as tmp:
        target=Path(tmp)/'candidate'
        shutil.copytree(ROOT/'results/reproduced',target)
        p=target/'exact/budgets_u1.json';original=json.loads(p.read_text())
        for name,field in [('changed_query_count','rank_queries'),('changed_source_range','initial_set_stop'),('measurement_only','cpu_seconds')]:
            obj=copy.deepcopy(original);obj[field]+=1;p.write_text(json.dumps(obj))
            out=Path(tmp)/'comparison.json'
            done=subprocess.run([sys.executable,str(ROOT/'tools/compare_results.py'),'--candidate',str(target),'--output',str(out)],capture_output=True,text=True,timeout=15)
            should_accept=name=='measurement_only'
            assert (done.returncode==0)==should_accept,(name,done.stdout,done.stderr)
            observations.append({'case':name,'accepted':done.returncode==0,'expected_acceptance':should_accept})
        p.write_text(json.dumps(original));p.unlink()
        done=subprocess.run([sys.executable,str(ROOT/'tools/compare_results.py'),'--candidate',str(target),'--output',str(Path(tmp)/'missing.json')],capture_output=True,text=True,timeout=15)
        assert done.returncode!=0
        observations.append({'case':'missing_result','accepted':False,'expected_acceptance':False})
    after=resource.getrusage(resource.RUSAGE_CHILDREN)
    data={'cases':observations,'mismatches':0,'parent_cpu_seconds':time.process_time()-start,'child_cpu_seconds':after.ru_utime+after.ru_stime-before.ru_utime-before.ru_stime}
    (ROOT/'results/comparison-controls.json').write_text(json.dumps(data,indent=2)+'\n')
    print(json.dumps(data,indent=2))
if __name__=='__main__':main()
